# Generated by Django 6.0.5 on 2026-05-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='url_poster',
            field=models.URLField(blank=True, help_text='Link da imagem do poster', null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='url_video',
            field=models.URLField(blank=True, help_text='Link do filme no Internet Archive', null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
