# Generated by Django 6.0.5 on 2026-05-18 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_filme_url_poster_filme_url_video_alter_filme_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='nota',
            field=models.IntegerField(default=5, help_text='Nota de 1 a 5 estrelas'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='filmes.filme')),
            ],
        ),
    ]
