# Generated by Django 6.0.5 on 2026-05-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_filme_nota_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='nota',
        ),
        migrations.AddField(
            model_name='comentario',
            name='nota',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='filme',
            name='url_poster',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='url_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
